<?php

$labels = array();
$labels['application_passwords'] = 'Anwendungsspezifische Passwörter';

// Used in step 1 when creating new password
$labels['new_application_step1_legend'] = 'Schritt 1 von 2: Neues anwendungsspezifisches Passwort generieren';
$labels['new_application_step1_description'] = 'Geben Sie einen Namen ein, der auf die Funktion dieser Anwendung hinweist, wie zum Beispiel "Christians Android", "Outlook - zu Hause", "Thunderbird", ... .';
$labels['name'] = 'Name:';
$labels['create_password'] = 'Password generieren';

// Used in step 2 when creating new password
$labels['new_application_step2_legend'] = 'Schritt 2 von 2: Erstelltes anwendungsspezifisches Passwort eingeben';
$labels['new_application_step2_description'] = 'Sie können jetzt Ihr neues anwendungsspezifisches Passwort in Ihre Anwendung eingeben. Mit diesem Passwort erhalten Sie uneingeschränkten Zugriff auf Ihr E-Mail-Konto. Aus Sicherheitsgründen wird es nicht erneut angezeigt:';

// Used in listing of existing passwords
$labels['existing_application_passwords'] = 'Existierende Passwörter';
$labels['applications'] = 'Ihre anwendungsspezifischen Passwörter';
$labels['date_created'] = 'Erstellungsdatum';

$messages = array();

?>
